apiVersion: apps/v1
kind: Deployment
metadata:
  name: StoreManage
  labels:
    app: StoreManage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: StoreManage
  template:
    metadata:
      labels:
        app: StoreManage
    spec:
      containers:
        - name: StoreManage
          image: username/StoreManage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5